// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zshkpncqhwwilxwreiub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzaGtwbmNxaHd3aWx4d3JlaXViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyOTk0OTcsImV4cCI6MjA2Mzg3NTQ5N30.3HJ6KLn0wsgJ2AM8_8022HLeY3e6KQhPHcZDNWQWr8g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);